/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lftechnology.ticketbookingsystem.admin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Movie service. Represents a row in the &quot;AD_Movie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lftechnology.ticketbookingsystem.admin.model.impl.MovieModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lftechnology.ticketbookingsystem.admin.model.impl.MovieImpl}.
 * </p>
 *
 * @author sudipshrestha
 * @see Movie
 * @see com.lftechnology.ticketbookingsystem.admin.model.impl.MovieImpl
 * @see com.lftechnology.ticketbookingsystem.admin.model.impl.MovieModelImpl
 * @generated
 */
public interface MovieModel extends BaseModel<Movie> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a movie model instance should use the {@link Movie} interface instead.
	 */

	/**
	 * Returns the primary key of this movie.
	 *
	 * @return the primary key of this movie
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this movie.
	 *
	 * @param primaryKey the primary key of this movie
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this movie.
	 *
	 * @return the ID of this movie
	 */
	public long getId();

	/**
	 * Sets the ID of this movie.
	 *
	 * @param id the ID of this movie
	 */
	public void setId(long id);

	/**
	 * Returns the moviename of this movie.
	 *
	 * @return the moviename of this movie
	 */
	@AutoEscape
	public String getMoviename();

	/**
	 * Sets the moviename of this movie.
	 *
	 * @param moviename the moviename of this movie
	 */
	public void setMoviename(String moviename);

	/**
	 * Returns the directorname of this movie.
	 *
	 * @return the directorname of this movie
	 */
	@AutoEscape
	public String getDirectorname();

	/**
	 * Sets the directorname of this movie.
	 *
	 * @param directorname the directorname of this movie
	 */
	public void setDirectorname(String directorname);

	/**
	 * Returns the shift_id of this movie.
	 *
	 * @return the shift_id of this movie
	 */
	public long getShift_id();

	/**
	 * Sets the shift_id of this movie.
	 *
	 * @param shift_id the shift_id of this movie
	 */
	public void setShift_id(long shift_id);

	/**
	 * Returns the hall_id of this movie.
	 *
	 * @return the hall_id of this movie
	 */
	public long getHall_id();

	/**
	 * Sets the hall_id of this movie.
	 *
	 * @param hall_id the hall_id of this movie
	 */
	public void setHall_id(long hall_id);

	/**
	 * Returns the ticket_id of this movie.
	 *
	 * @return the ticket_id of this movie
	 */
	public long getTicket_id();

	/**
	 * Sets the ticket_id of this movie.
	 *
	 * @param ticket_id the ticket_id of this movie
	 */
	public void setTicket_id(long ticket_id);

	/**
	 * Returns the company ID of this movie.
	 *
	 * @return the company ID of this movie
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this movie.
	 *
	 * @param companyId the company ID of this movie
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this movie.
	 *
	 * @return the group ID of this movie
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this movie.
	 *
	 * @param groupId the group ID of this movie
	 */
	public void setGroupId(long groupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Movie movie);

	public int hashCode();

	public CacheModel<Movie> toCacheModel();

	public Movie toEscapedModel();

	public String toString();

	public String toXmlString();
}