/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lftechnology.ticketbookingsystem.admin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Shift service. Represents a row in the &quot;AD_Shift&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lftechnology.ticketbookingsystem.admin.model.impl.ShiftModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lftechnology.ticketbookingsystem.admin.model.impl.ShiftImpl}.
 * </p>
 *
 * @author sudipshrestha
 * @see Shift
 * @see com.lftechnology.ticketbookingsystem.admin.model.impl.ShiftImpl
 * @see com.lftechnology.ticketbookingsystem.admin.model.impl.ShiftModelImpl
 * @generated
 */
public interface ShiftModel extends BaseModel<Shift> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shift model instance should use the {@link Shift} interface instead.
	 */

	/**
	 * Returns the primary key of this shift.
	 *
	 * @return the primary key of this shift
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this shift.
	 *
	 * @param primaryKey the primary key of this shift
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this shift.
	 *
	 * @return the ID of this shift
	 */
	public long getId();

	/**
	 * Sets the ID of this shift.
	 *
	 * @param id the ID of this shift
	 */
	public void setId(long id);

	/**
	 * Returns the shiftname of this shift.
	 *
	 * @return the shiftname of this shift
	 */
	@AutoEscape
	public String getShiftname();

	/**
	 * Sets the shiftname of this shift.
	 *
	 * @param shiftname the shiftname of this shift
	 */
	public void setShiftname(String shiftname);

	/**
	 * Returns the time of this shift.
	 *
	 * @return the time of this shift
	 */
	@AutoEscape
	public String getTime();

	/**
	 * Sets the time of this shift.
	 *
	 * @param time the time of this shift
	 */
	public void setTime(String time);

	/**
	 * Returns the company ID of this shift.
	 *
	 * @return the company ID of this shift
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this shift.
	 *
	 * @param companyId the company ID of this shift
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this shift.
	 *
	 * @return the group ID of this shift
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this shift.
	 *
	 * @param groupId the group ID of this shift
	 */
	public void setGroupId(long groupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Shift shift);

	public int hashCode();

	public CacheModel<Shift> toCacheModel();

	public Shift toEscapedModel();

	public String toString();

	public String toXmlString();
}